apiVersion: apps/v1
kind: Deployment 
metadata:
  name: app 
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret 
      containers:
        - name: app 
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: base-api-secret 
                  key: DATABASE_URL
            - name: JWT_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: base-api-secret
                  key: JWT_SECRETKEY
