apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: app

spec:
  tls:
    - hosts:
        - api.kzt.biz.id
      secretName: base-api-tls

  rules:
    - host: api.kzt.biz.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
