apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql 
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 18.7.13
      helm:
        valueFiles:
          - $values/infrastructure/postgresql/values.yaml

    - repoURL: https://github.com/WanXSky/homelab-gitops.git 
      targetRevision: main
      ref: values 

  destination:
    server: https://kubernetes.default.svc
    namespace: database

  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
