apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../templates/node-api/base/ 
namespace: production
namePrefix: base-api 
images:
  - name: nginx
    newName: ghcr.io/wanxsky/base-api
    newTag: ec1d70d
patches:
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml 
